DROP TABLE IF EXISTS Campus;
DROP TABLE IF EXISTS Confirmation_Code;
DROP TABLE IF EXISTS Role_Functionality;
DROP TABLE IF EXISTS Menu_Functionality;
DROP TABLE IF EXISTS Functionality;
DROP TABLE IF EXISTS Menu;
DROP TABLE IF EXISTS Request;
DROP TABLE IF EXISTS Request_Status;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS Settings;
DROP TABLE IF EXISTS Status;
DROP TABLE IF EXISTS Case_Info;

